# -*- coding: utf-8 -*-
"""Lab2task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B_fm2iJ-3-XwxajstidKLAy9o3nqYGQI

1. Matplotlib

2. Numpy
"""



"""3. List"""

#Creating List
numbers = [1,2,3,4,5,6,7,8,9,10]
total = sum(numbers)
maximum = max(numbers)
minimum = min(numbers)
print(f"Sum: {total}")
print(f"Maximum: {maximum}")
print(f"Minimum: {minimum}")

#Add and Remove
numbers.append(3)
numbers.remove(5)
print(f"Updated List: {numbers}")


# Sorting - Ascending Order
numbers_ascending = sorted(numbers)  # Creates new sorted list
print(f"Ascending Order: {numbers_ascending}")

# Sorting - Descending Order
numbers_descending = sorted(numbers, reverse=True)  # Creates new sorted list in reverse
print(f"Descending Order: {numbers_descending}")

"""4. Tuple

"""

fruits =("Apples","Mangoes","Banana","Grapes","Oranges")
print(f"Second Element: {fruits[1]}")
print(f"Last Element: {fruits[-1]}")
# fruits[1]="Watermelon"  # tuple is immutable
fruit_list = list(fruits)
fruit_list[1]="Watermelon"
fruits = tuple(fruit_list)
print(fruits)

fruits = ("Apples","Mangoes","Banana","Grapes","Oranges")
print(f"Second Element: {fruits[1]}")

fruits_list =list(fruits)
fruits_list[1]="Watermelon"

print(fruits)

"""5. Set"""

#Create Sets
set_1 ={1,2,3,4}
set_2 ={4,5,6,7,8}
print(f"Union: {set_1 | set_2}")
print(f"Intersection: {set_1 & set_2}")
print(f"Difference: {set_1-set_2}")

#Add and Remove
set_1.add(5)
set_2.remove(4)

#Print Updated Sets
print(set_1)
print(set_2)

"""6. Dictionary"""

#Creating Dictionary
students ={"Ali":88,"Ahmad":85,"Bilal":95,"Fatima":89,"Faryal":95}

#Changing Value of key Ali
students["Ali"]=90;

fruits = {"Apple","Apple","Apple"}

print(students)